# Generated by Django 2.1.2 on 2020-11-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.Resp')),
                ('id_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.Horario')),
            ],
        ),
        migrations.RenameField(
            model_name='dadospessoais',
            old_name='TelefoneResponsavel',
            new_name='TelefoneResp',
        ),
    ]
