from django.db import models
from django.contrib.auth.models import User


class Horario(models.Model):
    primeiraAulaS = models.CharField(max_length=40, null=False, blank=False)
    segundaAulaS = models.CharField(max_length=40, null=False, blank=False)
    terceiraAulaS = models.CharField(max_length=40, null=False, blank=False)
    quartaAulaS = models.CharField(max_length=40, null=False, blank=False)
    quintaAulaS = models.CharField(max_length=40, null=False, blank=False)
    sextaAulaS = models.CharField(max_length=40, null=False, blank=False)
    setimaAulaS = models.CharField(max_length=40, null=False, blank=False)
    oitavaAulaS = models.CharField(max_length=40, null=False, blank=False)
    nonaAulaS = models.CharField(max_length=40, null=False, blank=False)
    decimaAulaS = models.CharField(max_length=40, null=False, blank=False)

    primeiraAulaT = models.CharField(max_length=40, null=False, blank=False)
    segundaAulaT = models.CharField(max_length=40, null=False, blank=False)
    terceiraAulaT = models.CharField(max_length=40, null=False, blank=False)
    quartaAulaT = models.CharField(max_length=40, null=False, blank=False)
    quintaAulaT = models.CharField(max_length=40, null=False, blank=False)
    sextaAulaT = models.CharField(max_length=40, null=False, blank=False)
    setimaAulaT = models.CharField(max_length=40, null=False, blank=False)
    oitavaAulaT = models.CharField(max_length=40, null=False, blank=False)
    nonaAulaT = models.CharField(max_length=40, null=False, blank=False)
    decimaAulaT = models.CharField(max_length=40, null=False, blank=False)

    primeiraAulaQ = models.CharField(max_length=40, null=False, blank=False)
    segundaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    terceiraAulaQ = models.CharField(max_length=40, null=False, blank=False)
    quartaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    quintaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    sextaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    setimaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    oitavaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    nonaAulaQ = models.CharField(max_length=40, null=False, blank=False)
    decimaAulaQ = models.CharField(max_length=40, null=False, blank=False)

    primeiraAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    segundaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    terceiraAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    quartaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    quintaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    sextaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    setimaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    oitavaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    nonaAulaQUI = models.CharField(max_length=40, null=False, blank=False)
    decimaAulaQUI = models.CharField(max_length=40, null=False, blank=False)

    primeiraAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    segundaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    terceiraAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    quartaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    quintaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    sextaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    setimaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    oitavaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    nonaAulaSEX = models.CharField(max_length=40, null=False, blank=False)
    decimaAulaSEX = models.CharField(max_length=40, null=False, blank=False)

    turma = models.CharField(max_length=15, null=False, blank=False)


class Notas(models.Model):
    idAluno = models.ForeignKey(User, on_delete=models.CASCADE)
    PBFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MHistoria = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MBiologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MFilosofia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MGeografia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MPortuques = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MMatematica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MEdFisica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MEspanhol = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MIngles = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MQuimica = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)

    PBSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    SBSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    TBSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    QBSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    RecSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    MSociologia = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    turma = models.CharField(max_length=15, null=False, blank=False)


class Advertencia(models.Model):
    idAluno = models.ForeignKey(User, on_delete=models.CASCADE)
    Comum = models.CharField(max_length=2000)
    Media = models.CharField(max_length=2000)
    Grave = models.CharField(max_length=2000)

    turma = models.CharField(max_length=15, null=False, blank=False)


class Frequencia(models.Model):
    idAluno = models.ForeignKey(User, on_delete=models.CASCADE)
    JaneiroPB = models.IntegerField(blank=True, null=True)
    FevereiroPB = models.IntegerField(blank=True, null=True)
    MarcoPB = models.IntegerField(blank=True, null=True)
    AbrilPB = models.IntegerField(blank=True, null=True)
    MaioPB = models.IntegerField(blank=True, null=True)
    JunhoPB = models.IntegerField(blank=True, null=True)
    JulhoPB = models.IntegerField(blank=True, null=True)
    AgostoPB = models.IntegerField(blank=True, null=True)
    SetembroPB = models.IntegerField(blank=True, null=True)
    OutubroPB = models.IntegerField(blank=True, null=True)
    NovembroPB = models.IntegerField(blank=True, null=True)
    DesembroPB = models.IntegerField(blank=True, null=True)

    JaneiroGR = models.IntegerField(blank=True, null=True)
    FevereiroGR = models.IntegerField(blank=True, null=True)
    MarcoGR = models.IntegerField(blank=True, null=True)
    AbrilGR = models.IntegerField(blank=True, null=True)
    MaioGR = models.IntegerField(blank=True, null=True)
    JunhoGR = models.IntegerField(blank=True, null=True)
    JulhoGR = models.IntegerField(blank=True, null=True)
    AgostoGR = models.IntegerField(blank=True, null=True)
    SetembroGR = models.IntegerField(blank=True, null=True)
    OutubroGR = models.IntegerField(blank=True, null=True)
    NovembroGR = models.IntegerField(blank=True, null=True)
    DesembroGR = models.IntegerField(blank=True, null=True)

    JaneiroRD = models.IntegerField(blank=True, null=True)
    FevereiroRD = models.IntegerField(blank=True, null=True)
    MarcoRD = models.IntegerField(blank=True, null=True)
    AbrilRD = models.IntegerField(blank=True, null=True)
    MaioRD = models.IntegerField(blank=True, null=True)
    JunhoRD = models.IntegerField(blank=True, null=True)
    JulhoRD = models.IntegerField(blank=True, null=True)
    AgostoRD = models.IntegerField(blank=True, null=True)
    SetembroRD = models.IntegerField(blank=True, null=True)
    OutubroRD = models.IntegerField(blank=True, null=True)
    NovembroRD = models.IntegerField(blank=True, null=True)
    DesembroRD = models.IntegerField(blank=True, null=True)

    JaneiroLT = models.IntegerField(blank=True, null=True)
    FevereiroLT = models.IntegerField(blank=True, null=True)
    MarcoLT = models.IntegerField(blank=True, null=True)
    AbrilLT = models.IntegerField(blank=True, null=True)
    MaioLT = models.IntegerField(blank=True, null=True)
    JunhoLT = models.IntegerField(blank=True, null=True)
    JulhoLT = models.IntegerField(blank=True, null=True)
    AgostoLT = models.IntegerField(blank=True, null=True)
    SetembroLT = models.IntegerField(blank=True, null=True)
    OutubroLT = models.IntegerField(blank=True, null=True)
    NovembroLT = models.IntegerField(blank=True, null=True)
    DesembroLT = models.IntegerField(blank=True, null=True)

    JaneiroBIO = models.IntegerField(blank=True, null=True)
    FevereiroBIO = models.IntegerField(blank=True, null=True)
    MarcoBIO = models.IntegerField(blank=True, null=True)
    AbrilBIO = models.IntegerField(blank=True, null=True)
    MaioBIO = models.IntegerField(blank=True, null=True)
    JunhoBIO = models.IntegerField(blank=True, null=True)
    JulhoBIO = models.IntegerField(blank=True, null=True)
    AgostoBIO = models.IntegerField(blank=True, null=True)
    SetembroBIO = models.IntegerField(blank=True, null=True)
    OutubroBIO = models.IntegerField(blank=True, null=True)
    NovembroBIO = models.IntegerField(blank=True, null=True)
    DesembroBIO = models.IntegerField(blank=True, null=True)

    JaneiroEDF = models.IntegerField(blank=True, null=True)
    FevereiroEDF = models.IntegerField(blank=True, null=True)
    MarcoEDF = models.IntegerField(blank=True, null=True)
    AbrilEDF = models.IntegerField(blank=True, null=True)
    MaioEDF = models.IntegerField(blank=True, null=True)
    JunhoEDF = models.IntegerField(blank=True, null=True)
    JulhoEDF = models.IntegerField(blank=True, null=True)
    AgostoEDF = models.IntegerField(blank=True, null=True)
    SetembroEDF = models.IntegerField(blank=True, null=True)
    OutubroEDF = models.IntegerField(blank=True, null=True)
    NovembroEDF = models.IntegerField(blank=True, null=True)
    DesembroEDF = models.IntegerField(blank=True, null=True)

    JaneiroFIL = models.IntegerField(blank=True, null=True)
    FevereiroFIL = models.IntegerField(blank=True, null=True)
    MarcoFIL = models.IntegerField(blank=True, null=True)
    AbrilFIL = models.IntegerField(blank=True, null=True)
    MaioFIL = models.IntegerField(blank=True, null=True)
    JunhoFIL = models.IntegerField(blank=True, null=True)
    JulhoFIL = models.IntegerField(blank=True, null=True)
    AgostoFIL = models.IntegerField(blank=True, null=True)
    SetembroFIL = models.IntegerField(blank=True, null=True)
    OutubroFIL = models.IntegerField(blank=True, null=True)
    NovembroFIL = models.IntegerField(blank=True, null=True)
    DesembroFIL = models.IntegerField(blank=True, null=True)

    JaneiroFSK = models.IntegerField(blank=True, null=True)
    FevereiroFSK = models.IntegerField(blank=True, null=True)
    MarcoFSK = models.IntegerField(blank=True, null=True)
    AbrilFSK = models.IntegerField(blank=True, null=True)
    MaioFSK = models.IntegerField(blank=True, null=True)
    JunhoFSK = models.IntegerField(blank=True, null=True)
    JulhoFSK = models.IntegerField(blank=True, null=True)
    AgostoFSK = models.IntegerField(blank=True, null=True)
    SetembroFSK = models.IntegerField(blank=True, null=True)
    OutubroFSK = models.IntegerField(blank=True, null=True)
    NovembroFSK = models.IntegerField(blank=True, null=True)
    DesembroFSK = models.IntegerField(blank=True, null=True)

    JaneiroGEO = models.IntegerField(blank=True, null=True)
    FevereiroGEO = models.IntegerField(blank=True, null=True)
    MarcoGEO = models.IntegerField(blank=True, null=True)
    AbrilGEO = models.IntegerField(blank=True, null=True)
    MaioGEO = models.IntegerField(blank=True, null=True)
    JunhoGEO = models.IntegerField(blank=True, null=True)
    JulhoGEO = models.IntegerField(blank=True, null=True)
    AgostoGEO = models.IntegerField(blank=True, null=True)
    SetembroGEO = models.IntegerField(blank=True, null=True)
    OutubroGEO = models.IntegerField(blank=True, null=True)
    NovembroGEO = models.IntegerField(blank=True, null=True)
    DesembroGEO = models.IntegerField(blank=True, null=True)

    JaneiroHIS = models.IntegerField(blank=True, null=True)
    FevereiroHIS = models.IntegerField(blank=True, null=True)
    MarcoHIS = models.IntegerField(blank=True, null=True)
    AbrilHIS = models.IntegerField(blank=True, null=True)
    MaioHIS = models.IntegerField(blank=True, null=True)
    JunhoHIS = models.IntegerField(blank=True, null=True)
    JulhoHIS = models.IntegerField(blank=True, null=True)
    AgostoHIS = models.IntegerField(blank=True, null=True)
    SetembroHIS = models.IntegerField(blank=True, null=True)
    OutubroHIS = models.IntegerField(blank=True, null=True)
    NovembroHIS = models.IntegerField(blank=True, null=True)
    DesembroHIS = models.IntegerField(blank=True, null=True)

    JaneiroING = models.IntegerField(blank=True, null=True)
    FevereiroING = models.IntegerField(blank=True, null=True)
    MarcoING = models.IntegerField(blank=True, null=True)
    AbrilING = models.IntegerField(blank=True, null=True)
    MaioING = models.IntegerField(blank=True, null=True)
    JunhoING = models.IntegerField(blank=True, null=True)
    JulhoING = models.IntegerField(blank=True, null=True)
    AgostoING = models.IntegerField(blank=True, null=True)
    SetembroING = models.IntegerField(blank=True, null=True)
    OutubroING = models.IntegerField(blank=True, null=True)
    NovembroING = models.IntegerField(blank=True, null=True)
    DesembroING = models.IntegerField(blank=True, null=True)

    JaneiroESP = models.IntegerField(blank=True, null=True)
    FevereiroESP = models.IntegerField(blank=True, null=True)
    MarcoESP = models.IntegerField(blank=True, null=True)
    AbrilESP = models.IntegerField(blank=True, null=True)
    MaioESP = models.IntegerField(blank=True, null=True)
    JunhoESP = models.IntegerField(blank=True, null=True)
    JulhoESP = models.IntegerField(blank=True, null=True)
    AgostoESP = models.IntegerField(blank=True, null=True)
    SetembroESP = models.IntegerField(blank=True, null=True)
    OutubroESP = models.IntegerField(blank=True, null=True)
    NovembroESP = models.IntegerField(blank=True, null=True)
    DesembroESP = models.IntegerField(blank=True, null=True)

    JaneiroMAT = models.IntegerField(blank=True, null=True)
    FevereiroMAT = models.IntegerField(blank=True, null=True)
    MarcoMAT = models.IntegerField(blank=True, null=True)
    AbrilMAT = models.IntegerField(blank=True, null=True)
    MaioMAT = models.IntegerField(blank=True, null=True)
    JunhoMAT = models.IntegerField(blank=True, null=True)
    JulhoMAT = models.IntegerField(blank=True, null=True)
    AgostoMAT = models.IntegerField(blank=True, null=True)
    SetembroMAT = models.IntegerField(blank=True, null=True)
    OutubroMAT = models.IntegerField(blank=True, null=True)
    NovembroMAT = models.IntegerField(blank=True, null=True)
    DesembroMAT = models.IntegerField(blank=True, null=True)

    JaneiroGEM = models.IntegerField(blank=True, null=True)
    FevereiroGEM = models.IntegerField(blank=True, null=True)
    MarcoGEM = models.IntegerField(blank=True, null=True)
    AbrilGEM = models.IntegerField(blank=True, null=True)
    MaioGEM = models.IntegerField(blank=True, null=True)
    JunhoGEM = models.IntegerField(blank=True, null=True)
    JulhoGEM = models.IntegerField(blank=True, null=True)
    AgostoGEM = models.IntegerField(blank=True, null=True)
    SetembroGEM = models.IntegerField(blank=True, null=True)
    OutubroGEM = models.IntegerField(blank=True, null=True)
    NovembroGEM = models.IntegerField(blank=True, null=True)
    DesembroGEM = models.IntegerField(blank=True, null=True)

    JaneiroALG = models.IntegerField(blank=True, null=True)
    FevereiroALG = models.IntegerField(blank=True, null=True)
    MarcoALG = models.IntegerField(blank=True, null=True)
    AbrilALG = models.IntegerField(blank=True, null=True)
    MaioALG = models.IntegerField(blank=True, null=True)
    JunhoALG = models.IntegerField(blank=True, null=True)
    JulhoALG = models.IntegerField(blank=True, null=True)
    AgostoALG = models.IntegerField(blank=True, null=True)
    SetembroALG = models.IntegerField(blank=True, null=True)
    OutubroALG = models.IntegerField(blank=True, null=True)
    NovembroALG = models.IntegerField(blank=True, null=True)
    DesembroALG = models.IntegerField(blank=True, null=True)

    JaneiroQUI = models.IntegerField(blank=True, null=True)
    FevereiroQUI = models.IntegerField(blank=True, null=True)
    MarcoQUI = models.IntegerField(blank=True, null=True)
    AbrilQUI = models.IntegerField(blank=True, null=True)
    MaioQUI = models.IntegerField(blank=True, null=True)
    JunhoQUI = models.IntegerField(blank=True, null=True)
    JulhoQUI = models.IntegerField(blank=True, null=True)
    AgostoQUI = models.IntegerField(blank=True, null=True)
    SetembroQUI = models.IntegerField(blank=True, null=True)
    OutubroQUI = models.IntegerField(blank=True, null=True)
    NovembroQUI = models.IntegerField(blank=True, null=True)
    DesembroQUI = models.IntegerField(blank=True, null=True)

    JaneiroSOC = models.IntegerField(blank=True, null=True)
    FevereiroSOC= models.IntegerField(blank=True, null=True)
    MarcoSOC = models.IntegerField(blank=True, null=True)
    AbrilSOC = models.IntegerField(blank=True, null=True)
    MaioSOC = models.IntegerField(blank=True, null=True)
    JunhoSOC = models.IntegerField(blank=True, null=True)
    JulhoSOC = models.IntegerField(blank=True, null=True)
    AgostoSOC = models.IntegerField(blank=True, null=True)
    SetembroSOC = models.IntegerField(blank=True, null=True)
    OutubroSOC = models.IntegerField(blank=True, null=True)
    NovembroSOC = models.IntegerField(blank=True, null=True)
    DesembroSOC = models.IntegerField(blank=True, null=True)

    turma = models.CharField(max_length=15, null=False, blank=False)


class Conteudo(models.Model):
    PortuquesBasico = models.FileField(upload_to="%Y/%m/%d/")
    Gramatica = models.FileField(upload_to="%Y/%m/%d/")
    Redacao = models.FileField(upload_to="%Y/%m/%d/")
    Leitura = models.FileField(upload_to="%Y/%m/%d/")
    Biologia = models.FileField(upload_to="%Y/%m/%d/")
    EducacaoFisica = models.FileField(upload_to="%Y/%m/%d/")
    Filosofia = models.FileField(upload_to="%Y/%m/%d/")
    Fisica = models.FileField(upload_to="%Y/%m/%d/")
    Geografia = models.FileField(upload_to="%Y/%m/%d/")
    Historia = models.FileField(upload_to="%Y/%m/%d/")
    Ingles = models.FileField(upload_to="%Y/%m/%d/")
    Espanhol = models.FileField(upload_to="%Y/%m/%d/")
    MatematicaBasica = models.FileField(upload_to="%Y/%m/%d/")
    Geometria = models.FileField(upload_to="%Y/%m/%d/")
    Algebra = models.FileField(upload_to="%Y/%m/%d/")
    Quimica = models.FileField(upload_to="%Y/%m/%d/")
    Sociologia = models.FileField(upload_to="%Y/%m/%d/")

    turma = models.CharField(max_length=15, null=False, blank=False)


class DadosPessoais(models.Model):
    idAluno = models.ForeignKey(User, on_delete=models.CASCADE)
    Foto = models.FileField(upload_to="%Y/%m/%d/")
    Telefone = models.IntegerField()
    Nome = models.CharField(max_length=100, null=False, blank=False)
    Idade = models.IntegerField()
    CPF = models.CharField(max_length=15, null=False, blank=False)
    RG = models.IntegerField()
    NomeResponsavel = models.CharField(max_length=100, null=False, blank=False)
    TelefoneResp = models.IntegerField()
    CPF_Responsavel = models.CharField(max_length=15, null=False, blank=False)
    RG_Responsavel = models.IntegerField()

    turma = models.CharField(max_length=15, null=False, blank=False)


class Resp(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    turma = models.CharField(max_length=100, null=False, blank=False)
    senha = models.CharField(max_length=255, null=False, blank=False)
    nome_aluno = models.CharField(max_length=100, null=False, blank=False)
    matricula_aluno = models.IntegerField()


class RespSuper(models.Model):
    id_resp = models.IntegerField()
    id_aluno = models.ForeignKey(User, on_delete=models.CASCADE)


class Test(models.Model):
    id_resp = models.ForeignKey(Horario, on_delete=models.CASCADE)
    id_aluno = models.ForeignKey(Resp, on_delete=models.CASCADE)